import { existsSync, mkdirSync, cpSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import chalk from 'chalk';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Initialize ProAgents in the current project
 */
export async function initCommand(options = {}) {
  const targetDir = process.cwd();
  const proagentsDir = join(targetDir, 'proagents');
  const sourceDir = join(__dirname, '..', '..', 'proagents');

  console.log('\n' + chalk.bold.blue('ProAgents Initialization'));
  console.log(chalk.blue('========================\n'));

  // Check if already initialized
  if (existsSync(proagentsDir) && !options.force) {
    console.log(chalk.yellow('⚠️  ProAgents is already initialized in this project.'));
    console.log(chalk.gray('   Use --force to overwrite.\n'));
    return;
  }

  try {
    // Copy proagents folder
    console.log(chalk.gray('Copying framework files...'));
    cpSync(sourceDir, proagentsDir, { recursive: true, force: options.force || false });
    console.log(chalk.green('✓ Framework files copied to ./proagents/'));

    // Create config if not skipped
    if (!options.skipConfig) {
      const configPath = join(targetDir, 'proagents.config.yaml');
      if (!existsSync(configPath)) {
        const configSource = join(sourceDir, 'proagents.config.yaml');
        if (existsSync(configSource)) {
          cpSync(configSource, configPath);
          console.log(chalk.green('✓ Created proagents.config.yaml'));
        }
      }
    }

    // Create docs folder structure for client-facing documentation
    const docsDir = join(targetDir, 'docs');
    const releasesDir = join(docsDir, 'releases');
    const apiDocsDir = join(docsDir, 'api');

    if (!existsSync(docsDir)) {
      mkdirSync(docsDir, { recursive: true });
    }
    if (!existsSync(releasesDir)) {
      mkdirSync(releasesDir, { recursive: true });
      // Create releases index
      writeFileSync(join(releasesDir, 'README.md'),
`# Release History

This folder contains version-specific release notes.

| Version | Date | Description |
|---------|------|-------------|
| v1.0.0 | TBD | Initial release |

---

Generated by [ProAgents](https://github.com/prakashpro3/proAgents)
`);
    }
    if (!existsSync(apiDocsDir)) {
      mkdirSync(apiDocsDir, { recursive: true });
    }
    console.log(chalk.green('✓ Created docs/ folder structure'));

    // Create placeholder CHANGELOG.md if not exists
    const changelogPath = join(targetDir, 'CHANGELOG.md');
    if (!existsSync(changelogPath)) {
      writeFileSync(changelogPath,
`# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Added
- Initial project setup

---

*Generated by [ProAgents](https://github.com/prakashpro3/proAgents)*
`);
      console.log(chalk.green('✓ Created CHANGELOG.md'));
    }

    // Create placeholder RELEASE_NOTES.md if not exists
    const releaseNotesPath = join(targetDir, 'RELEASE_NOTES.md');
    if (!existsSync(releaseNotesPath)) {
      writeFileSync(releaseNotesPath,
`# Release Notes

**Current Version:** Unreleased
**Last Updated:** ${new Date().toISOString().split('T')[0]}

## Overview

This document contains release notes for client and stakeholder communication.

## Latest Release

No releases yet. Use \`/doc-release\` to generate release notes.

---

*Generated by [ProAgents](https://github.com/prakashpro3/proAgents)*
`);
      console.log(chalk.green('✓ Created RELEASE_NOTES.md'));
    }

    // Copy PROAGENTS.md to project root (AI context file)
    const proagentsMdPath = join(targetDir, 'PROAGENTS.md');
    const proagentsMdSource = join(sourceDir, 'PROAGENTS.md');
    if (!existsSync(proagentsMdPath) || options.force) {
      if (existsSync(proagentsMdSource)) {
        cpSync(proagentsMdSource, proagentsMdPath);
        console.log(chalk.green('✓ Created PROAGENTS.md (AI context file)'));
      }
    }

    // Success message
    console.log(chalk.green('\n✓ ProAgents initialized successfully!\n'));

    // Next steps - Updated for universal AI usage
    console.log(chalk.bold('How to Use with Any AI:'));
    console.log(chalk.white('───────────────────────'));
    console.log(chalk.yellow('1. Start your AI (Claude, ChatGPT, Gemini, Copilot, etc.)'));
    console.log(chalk.yellow('2. Tell the AI:'));
    console.log(chalk.cyan('   "Read PROAGENTS.md and follow the ProAgents workflow"'));
    console.log(chalk.yellow('3. Then use commands like:'));
    console.log(chalk.cyan('   /feature-start "your feature name"'));
    console.log(chalk.cyan('   /fix "bug description"'));
    console.log(chalk.cyan('   /status'));
    console.log(chalk.cyan('   /help'));
    console.log('\n' + chalk.bold('Files Created:'));
    console.log(chalk.gray('  PROAGENTS.md      → AI instructions (share with any AI)'));
    console.log(chalk.gray('  CHANGELOG.md      → Client-facing changelog'));
    console.log(chalk.gray('  RELEASE_NOTES.md  → Client-facing release notes'));
    console.log(chalk.gray('  proagents/        → Framework files\n'));

  } catch (error) {
    console.error(chalk.red('\n✗ Error initializing ProAgents:'));
    console.error(chalk.red(error.message));
    process.exit(1);
  }
}
