import { existsSync, mkdirSync, cpSync, writeFileSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import chalk from 'chalk';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Initialize ProAgents in the current project
 */
export async function initCommand(options = {}) {
  const targetDir = process.cwd();
  const proagentsDir = join(targetDir, 'proagents');
  const sourceDir = join(__dirname, '..', '..', 'proagents');

  console.log('\n' + chalk.bold.blue('ProAgents Initialization'));
  console.log(chalk.blue('========================\n'));

  // Check if already initialized
  if (existsSync(proagentsDir) && !options.force) {
    console.log(chalk.yellow('⚠️  ProAgents is already initialized in this project.'));
    console.log(chalk.gray('   Use --force to overwrite.\n'));
    return;
  }

  try {
    // Copy proagents folder
    console.log(chalk.gray('Copying framework files...'));
    cpSync(sourceDir, proagentsDir, { recursive: true, force: options.force || false });
    console.log(chalk.green('✓ Framework files copied to ./proagents/'));

    // Create config if not skipped
    if (!options.skipConfig) {
      const configPath = join(targetDir, 'proagents.config.yaml');
      if (!existsSync(configPath)) {
        const configSource = join(sourceDir, 'proagents.config.yaml');
        if (existsSync(configSource)) {
          cpSync(configSource, configPath);
          console.log(chalk.green('✓ Created proagents.config.yaml'));
        }
      }
    }

    // Create docs folder structure for client-facing documentation
    const docsDir = join(targetDir, 'docs');
    const releasesDir = join(docsDir, 'releases');
    const apiDocsDir = join(docsDir, 'api');

    if (!existsSync(docsDir)) {
      mkdirSync(docsDir, { recursive: true });
    }
    if (!existsSync(releasesDir)) {
      mkdirSync(releasesDir, { recursive: true });
      // Create releases index
      writeFileSync(join(releasesDir, 'README.md'),
`# Release History

This folder contains version-specific release notes.

| Version | Date | Description |
|---------|------|-------------|
| v1.0.0 | TBD | Initial release |

---

Generated by [ProAgents](https://github.com/prakashpro3/proAgents)
`);
    }
    if (!existsSync(apiDocsDir)) {
      mkdirSync(apiDocsDir, { recursive: true });
    }
    console.log(chalk.green('✓ Created docs/ folder structure'));

    // Create placeholder CHANGELOG.md if not exists
    const changelogPath = join(targetDir, 'CHANGELOG.md');
    if (!existsSync(changelogPath)) {
      writeFileSync(changelogPath,
`# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Added
- Initial project setup

---

*Generated by [ProAgents](https://github.com/prakashpro3/proAgents)*
`);
      console.log(chalk.green('✓ Created CHANGELOG.md'));
    }

    // Create placeholder RELEASE_NOTES.md if not exists
    const releaseNotesPath = join(targetDir, 'RELEASE_NOTES.md');
    if (!existsSync(releaseNotesPath)) {
      writeFileSync(releaseNotesPath,
`# Release Notes

**Current Version:** Unreleased
**Last Updated:** ${new Date().toISOString().split('T')[0]}

## Overview

This document contains release notes for client and stakeholder communication.

## Latest Release

No releases yet. Use \`pa:release\` to generate release notes.

---

*Generated by [ProAgents](https://github.com/prakashpro3/proAgents)*
`);
      console.log(chalk.green('✓ Created RELEASE_NOTES.md'));
    }

    // Add ProAgents section to README.md (AI tools auto-read this)
    const readmePath = join(targetDir, 'README.md');
    const proagentsSection = `
<!-- PROAGENTS:START - AI Development Commands -->
## AI Commands (ProAgents)

This project uses [ProAgents](https://github.com/prakashpro3/proAgents). Commands use \`pa:\` prefix:

| Command | Description |
|---------|-------------|
| \`pa:help\` | Show all commands |
| \`pa:feature "name"\` | Start new feature |
| \`pa:fix "bug"\` | Quick bug fix |
| \`pa:status\` | Show progress |
| \`pa:release\` | Generate release notes |

For detailed commands, see \`./proagents/PROAGENTS.md\`
<!-- PROAGENTS:END -->

`;

    if (existsSync(readmePath)) {
      const readmeContent = readFileSync(readmePath, 'utf-8');
      if (!readmeContent.includes('PROAGENTS:START')) {
        // Prepend to existing README
        writeFileSync(readmePath, proagentsSection + readmeContent);
        console.log(chalk.green('✓ Added ProAgents commands to README.md'));
      }
    } else {
      // Create new README with ProAgents section
      writeFileSync(readmePath, proagentsSection + `# Project Name\n\nProject description.\n`);
      console.log(chalk.green('✓ Created README.md with ProAgents commands'));
    }

    // Success message
    console.log(chalk.green('\n✓ ProAgents initialized successfully!\n'));

    // Simple next steps
    console.log(chalk.bold('Usage:'));
    console.log(chalk.white('──────'));
    console.log('Type commands in any AI (prefix: pa:)');
    console.log(chalk.cyan('  pa:help              ') + chalk.gray('Show all commands'));
    console.log(chalk.cyan('  pa:feature "name"    ') + chalk.gray('Start new feature'));
    console.log(chalk.cyan('  pa:fix "bug"         ') + chalk.gray('Quick bug fix'));
    console.log(chalk.cyan('  pa:status            ') + chalk.gray('Show progress'));
    console.log(chalk.cyan('  pa:release           ') + chalk.gray('Generate release notes'));
    console.log('\n' + chalk.gray('Commands added to README.md - AI tools will see them automatically.\n'));

  } catch (error) {
    console.error(chalk.red('\n✗ Error initializing ProAgents:'));
    console.error(chalk.red(error.message));
    process.exit(1);
  }
}
